# Generated by Django 5.1.5 on 2025-02-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=255, verbose_name='apellidos')),
                ('nombres', models.CharField(max_length=255, verbose_name='nombres')),
                ('documento', models.IntegerField(verbose_name='documento')),
                ('foto', models.ImageField(null=True, upload_to='fotos/', verbose_name='foto')),
                ('qr', models.ImageField(null=True, upload_to='qrs/', verbose_name='qr')),
            ],
        ),
    ]
