# Generated by Django 5.1.5 on 2025-03-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_curso_estudiante_linea'),
    ]

    operations = [
        migrations.CreateModel(
            name='qrScan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_value', models.CharField(max_length=255)),
            ],
        ),
    ]
