# Generated by Django 5.1.5 on 2025-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_qrscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrscan',
            name='qr_value',
            field=models.IntegerField(max_length=255),
        ),
    ]
